//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateZugferd2_0_PdfDocument.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateZugferd2_0_PdfDocument.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xmlns:pdfaExtension=&quot;http://www.aiim.org/pdfa/ns/extension/&quot;
        ///    xmlns:pdfaSchema=&quot;http://www.aiim.org/pdfa/ns/schema#&quot;
        ///    xmlns:pdfaProperty=&quot;http://www.aiim.org/pdfa/ns/property#&quot;
        ///    xmlns:zf=&quot;urn:ferd:pdfa:CrossIndustryDocument:invoice:2p0#&quot;.
        /// </summary>
        internal static string xmlPart1 {
            get {
                return ResourceManager.GetString("xmlPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pdfaExtension:schemas&gt;
        ///    &lt;rdf:Bag&gt;
        ///     &lt;rdf:li&gt;
        ///      &lt;rdf:Description
        ///       pdfaSchema:schema=&quot;ZUGFeRD PDFA Extension Schema&quot;
        ///       pdfaSchema:namespaceURI=&quot;urn:ferd:pdfa:CrossIndustryDocument:invoice:2p0#&quot;
        ///       pdfaSchema:prefix=&quot;zf&quot;&gt;
        ///      &lt;pdfaSchema:property&gt;
        ///       &lt;rdf:Seq&gt;
        ///        &lt;rdf:li
        ///         pdfaProperty:name=&quot;DocumentFileName&quot;
        ///         pdfaProperty:valueType=&quot;Text&quot;
        ///         pdfaProperty:category=&quot;external&quot;
        ///         pdfaProperty:description=&quot;name of the embedded XML invoic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmlPart2 {
            get {
                return ResourceManager.GetString("xmlPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zf:ConformanceLevel=&quot;BASIC&quot;
        ///   zf:DocumentFileName=&quot;%filename%&quot;
        ///   zf:DocumentType=&quot;INVOICE&quot;
        ///   zf:Version=&quot;1.0&quot;.
        /// </summary>
        internal static string xmlPart3 {
            get {
                return ResourceManager.GetString("xmlPart3", resourceCulture);
            }
        }
    }
}
